IMS/Models/Supplier.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace IMS.Models
{
    public class Supplier
    {
        [Key]
        public int SupplierId { get; set; }

        [Required(ErrorMessage = "Name field required")]
        [Display(Name = "Name")]
        public string SupplierName { get; set; }

        [Required(ErrorMessage = "Address field required")]
        [Display(Name = "Address")]
        public string SupplierAddress { get; set; }

        [Required(ErrorMessage = "Phone number field required")]
        [Display(Name = "Phone Number")]
        public string SupplierContact { get; set; }

        public virtual ICollection<Stock> Stock { get; set; }

        public virtual ICollection<Purchases> Purchases { get; set; }


    }
}

IMS/Controllers/SupplierController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IMS.Data.Objects.Entities;
using IMS.Data.DbConnections.DAL;

namespace IMS.Controllers
{
    public class SupplierController : Controller
    {
        private IMS_DB db = new IMS_DB();

        // GET: /Supplier/
        public ActionResult Index()
        {
            return View(db.Suppliers.ToList());
        }


        // GET: /Supplier/Create
        public ActionResult Create()
        {
            var supplier = new Supplier();
            return PartialView("Create", supplier);
        }

        // POST: /Supplier/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="SupplierId,SupplierName,SupplierAddress,SupplierContact")] Supplier supplier)
        {
            if (ModelState.IsValid)
            {
                db.Suppliers.Add(supplier);
                db.SaveChanges();
                return Json(new { success = true });
            }

            return PartialView("Create", supplier);
        }

        // GET: /Supplier/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Supplier supplier = db.Suppliers.Find(id);
            if (supplier == null)
            {
                return HttpNotFound();
            }
            return PartialView("Edit", supplier);
        }

        // POST: /Supplier/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="SupplierId,SupplierName,SupplierAddress,SupplierContact")] Supplier supplier)
        {
            if (ModelState.IsValid)
            {
                db.Entry(supplier).State = EntityState.Modified;
                db.SaveChanges();
                return Json(new { success = true });
            }
            return PartialView("Edit", supplier);
        }

        // GET: /Supplier/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Supplier supplier = db.Suppliers.Find(id);
            if (supplier == null)
            {
                return HttpNotFound();
            }
            return PartialView("Delete", supplier);
        }

        // POST: /Supplier/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Supplier supplier = db.Suppliers.Find(id);
            db.Suppliers.Remove(supplier);
            db.SaveChanges();
            return Json(new { success = true });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

IMS/Views/Supplier/Create.cshtml
@model IMS.Data.Objects.Entities.Supplier

 <!--MODAL HEADER-->
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 class="modal-title">Add New Supplier</h3>

</div>

@using (Html.BeginForm("Create", "Supplier", FormMethod.Post))
{
    @Html.AntiForgeryToken()

     <!--MODAL BODY-->
    <div class="modal-body">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12 form-group">
                    @Html.LabelFor(model => model.SupplierName, new { @class = "control-label" })
                    @Html.TextBoxFor(model => model.SupplierName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.SupplierName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 form-group">
                    @Html.LabelFor(model => model.SupplierAddress, new { @class = "control-label bold" })
                    @Html.TextBoxFor(model => model.SupplierAddress, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.SupplierAddress, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 form-group">
                    @Html.LabelFor(model => model.SupplierContact, new { @class = "control-label" })
                    @Html.TextBoxFor(model => model.SupplierContact, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.SupplierContact, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    </div>

        <!--MODAL FOOTER-->
    <div class="modal-footer">
        <input class="btn btn-primary" type="submit" value="Save" />
        <button class="btn btn-warning" data-dismiss="modal">Close</button>
    </div>

}

<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script>
    $("form").removeData("validator");
    $("form").removeData("unobtrusiveValidation");
    $.validator.unobtrusive.parse("form");
</script>

IMS/Views/Supplier/Delete.cshtml
@model IMS.Data.Objects.Entities.Supplier

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 class="modal-title">Deleting Supplier</h3>
</div>

<div class="modal-body">
   <h3>
       Are you sure you want to delete @Html.DisplayFor(model => model.SupplierName)  ?
   </h3>
</div>
@using (Html.BeginForm("Delete", "Supplier", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="modal-footer">
        <input type="submit" value="Yes" class="btn btn-danger" />
        <button class="btn btn-warning" data-dismiss="modal">No</button>
    </div>
}

IMS/Views/Supplier/Edit.cshtml
@model IMS.Data.Objects.Entities.Supplier

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 class="modal-title">Editing @Html.DisplayFor(model => model.SupplierName)</h3>

</div>

@using (Html.BeginForm("Edit", "Supplier", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.SupplierId)
     <!--MODAL BODY-->
    <div class="modal-body">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12 form-group">
                    @Html.LabelFor(model => model.SupplierName, new { @class = "control-label" })
                    @Html.TextBoxFor(model => model.SupplierName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.SupplierName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 form-group">
                    @Html.LabelFor(model => model.SupplierAddress, new { @class = "control-label bold" })
                    @Html.TextBoxFor(model => model.SupplierAddress, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.SupplierAddress, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 form-group">
                    @Html.LabelFor(model => model.SupplierContact, new { @class = "control-label" })
                    @Html.TextBoxFor(model => model.SupplierContact, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.SupplierContact, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    </div>

        <!--MODAL FOOTER-->
    <div class="modal-footer">
        <input class="btn btn-primary" type="submit" value="Save" />
        <button class="btn btn-warning" data-dismiss="modal">Close</button>
    </div>

}

<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script>
    $("form").removeData("validator");
    $("form").removeData("unobtrusiveValidation");
    $.validator.unobtrusive.parse("form");
</script>

IMS/Views/Supplier/Index.cshtml
@model IEnumerable<IMS.Data.Objects.Entities.Supplier>

@{
    ViewBag.Title = "Index";
    var customer = new IMS.Data.Objects.Entities.Customer();
    var x = 1;
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    td {
        text-align: center;
        vertical-align: middle;
    }

    th {
        text-align: center;
        vertical-align: middle;
    }
</style>

<ul class="breadcrumb">
    <li><a href="@Url.Action("Index", "Dashboard")">Dashboard</a></li>
    <a href="@Url.Action("Create", "Supplier")" class="btn btn-primary btn-sm pull-right" data-modal=""><i style="color: red;" class="fa fa-2x fa-plus"></i> Add</a>
</ul>

<div class="row mt">
    <div class="col-lg-12">
        <div class="content-panel">
            <div style="padding: 20px;">
                <h4> SUPPLIERS </h4>
                <table class="table table-hover" id="myTable">
                    <thead>
                        <tr>
                            <th>
                                #
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.SupplierName)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.SupplierAddress)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.SupplierContact)
                            </th>
                            <th>
                                Actions
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @(x++)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.SupplierName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.SupplierAddress)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.SupplierContact)
                                </td>
                                <td>
                                    <a href="@Url.Action("Edit", "Supplier", new { id = item.SupplierId })" data-modal=""><i style="color: brown;" class="fa fa-2x fa-edit"></i></a>
                                    <a href="@Url.Action("Delete", "Supplier", new { id = item.SupplierId })" data-modal=""><i style="color: red;" class="fa fa-2x fa-trash"></i></a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div><!-- /content-panel -->
    </div><!-- /col-lg-4 -->
</div><!-- /row -->


<!-- modal placeholder-->
<div id='myModal' class='modal fade in'>
    <div class="modal-dialog">
        <div class="modal-content">
            <div id='myModalContent'></div>
        </div>
    </div>
</div>

<script src="~/Scripts/jquery-1.12.4.js"></script>
<script src="~/Scripts/Appjs/IMS.js"></script>

<script>
    $(document).ready(function () {
        $('#myTable').DataTable({
            columnDefs: [
                {
                    targets: [0, 1, 2],
                    className: 'dataTable'
                }
            ]
        });
    });
</script>