IMS/Models/Category.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace IMS.Models
{
    public class Category
    {
        [Key]
        public int CategoryId { get; set; }
        
        [Display(Name = "Category Name")]
        [Required(ErrorMessage = "Category name required")]
        public string CategoryName { get; set; }

        public virtual ICollection<Product> ProductVirtual { get; set; }
        public virtual ICollection<Stock> StockVirtual { get; set; }
    }
}

IMS/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IMS.Data.Objects.Entities;
using IMS.Data.DbConnections.DAL;
using PagedList;

namespace IMS.Controllers
{
    public class CategoryController : Controller
    {
        private IMS_DB db = new IMS_DB();

        // GET: /Category/
        public ActionResult Index()
        {
            return View(db.Category.ToList());
        }

        // GET: /Category/Create
        public ActionResult Create()
        {
            var category = new Category();
            return PartialView("", category);
        }

        // POST: /Category/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="CategoryId,CategoryName")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Category.Add(category);
                db.SaveChanges();
                return Json(new { success = true });
            }

            return PartialView("Create", category);
        }

        // GET: /Category/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Category.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return PartialView("Edit", category);
        }

        // POST: /Category/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="CategoryId,CategoryName")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Entry(category).State = EntityState.Modified;
                db.SaveChanges();
                return Json(new { success = true });
            }
            return PartialView("Edit", category);
        }

        // GET: /Category/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Category.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return PartialView("Delete", category);
        }

        // POST: /Category/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Category category = db.Category.Find(id);
            db.Category.Remove(category);
            db.SaveChanges();
            return Json(new { success = true });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

IMS/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IMS.Data.Objects.Entities;
using IMS.Data.DbConnections.DAL;

namespace IMS.Controllers
{
    public class ProductController : Controller
    {
        private IMS_DB db = new IMS_DB();

        // GET: /Product/
        [Route("Product/Index/{CategoryId}")]
        public ActionResult Index(int CategoryId)
        {
            var x = db.Category.Find(CategoryId);
            Session["categoryname"] = x.CategoryName;
            Session["categoryId"] = x.CategoryId;

            var product = db.Product.Where(p => p.CategoryId == CategoryId).ToList();
            return View(product);
        }

        // GET: /Product/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Product.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: /Product/Create
        public ActionResult Create()
        {
            var product = new Product();
            return PartialView("Create", product);
        }

        // POST: /Product/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProductId,ProductName,ProductQuantity,ProductDescription,CategoryId")] Product product)
        {
            if (ModelState.IsValid)
            {
                var p = new Product
                {
                    CategoryId = Convert.ToInt32(Session["categoryId"]),
                    ProductName = product.ProductName,
                    ProductDescription = product.ProductDescription,
                    ProductQuantity = product.ProductQuantity
                };
                db.Product.Add(p);
                db.SaveChanges();
                return Json(new { success = true });
            }

            return PartialView("Create", product);
        }

        // GET: /Product/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Product.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryId = new SelectList(db.Category, "CategoryId", "CategoryName", product.CategoryId);
            return PartialView("Edit", product);
        }

        // POST: /Product/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProductId,ProductName,ProductQuantity,ProductDescription,CategoryId")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return Json(new { success = true });
            }
            ViewBag.CategoryId = new SelectList(db.Category, "CategoryId", "CategoryName", product.CategoryId);
            return PartialView("Edit", product);
        }

        // GET: /Product/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Product.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return PartialView("Delete", product);
        }

        // POST: /Product/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Product product = db.Product.Find(id);
            db.Product.Remove(product);
            db.SaveChanges();
            return Json(new { success = true });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

IMS/Views/Category/Create.cshtml
@model IMS.Data.Objects.Entities.Category

@{
    ViewBag.Title = "Create";
}

<!--MODAL HEADER-->
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 class="modal-title">Add New Category</h3>

</div>

@using (Html.BeginForm("Create", "Category", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.CategoryId)

     <!--MODAL BODY-->
    <div class="modal-body">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12 form-group">
                    @Html.LabelFor(model => model.CategoryName, new { @class = "control-label" })
                    @Html.TextBoxFor(model => model.CategoryName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CategoryName, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    </div>

        <!--MODAL FOOTER-->
    <div class="modal-footer">
        <input class="btn btn-primary" type="submit" value="Save" />
        <button class="btn btn-warning" data-dismiss="modal">Close</button>
    </div>

}

<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script>
    $("form").removeData("validator");
    $("form").removeData("unobtrusiveValidation");
    $.validator.unobtrusive.parse("form");
</script>

IMS/Views/Category/Delete.cshtml
@model IMS.Data.Objects.Entities.Category

@{
    ViewBag.Title = "Delete";
}

<!--MODAL HEADER-->
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 class="modal-title">Deleting @Html.DisplayFor(model => model.CategoryName) Category</h3>
</div>

<!--MODAL BODY-->
<div class="modal-body">
    <h3>
        Are you sure you want to delete @Html.DisplayFor(model => model.CategoryName)  ?
    </h3>
</div>

@using (Html.BeginForm("Delete", "Category", FormMethod.Post))
{
    @Html.AntiForgeryToken()
<!--MODAL FOOTER-->
    <div class="modal-footer">
        <input type="submit" value="Yes" class="btn btn-danger" />
        <button class="btn btn-warning" data-dismiss="modal">No</button>
    </div>
}

IMS/Views/Category/Edit.cshtml
@model IMS.Data.Objects.Entities.Category

@{
    ViewBag.Title = "Edit";
}

<!--MODAL HEADER-->
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 class="modal-title">Editing @Html.DisplayFor(model => model.CategoryName)</h3>

</div>

@using (Html.BeginForm("Edit", "Category", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.CategoryId)

     <!--MODAL BODY-->
    <div class="modal-body">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12 form-group">
                    @Html.LabelFor(model => model.CategoryName, new { @class = "control-label" })
                    @Html.TextBoxFor(model => model.CategoryName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CategoryName, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    </div>

        <!--MODAL FOOTER-->
    <div class="modal-footer">
        <input class="btn btn-primary" type="submit" value="Save" />
        <button class="btn btn-warning" data-dismiss="modal">Close</button>
    </div>

}

<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script>
    $("form").removeData("validator");
    $("form").removeData("unobtrusiveValidation");
    $.validator.unobtrusive.parse("form");
</script>

IMS/Views/Category/Index.cshtml
@model IEnumerable<IMS.Data.Objects.Entities.Category>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    IMS.Data.DbConnections.DAL.IMS_DB db = new IMS.Data.DbConnections.DAL.IMS_DB();
    var x = 1;
}

<style>
    td {
        text-align: center;
        vertical-align: middle;
    }

    th {
        text-align: center;
        vertical-align: middle;
    }
    pdU{
        padding-right:10px;
    }
</style>

<ul class="breadcrumb">
    <li><a href="@Url.Action("Index", "Dashboard")">Dashboard</a></li>
    <a href="@Url.Action("Create", "Category")" class="btn btn-primary btn-sm pull-right" data-modal=""><i style="color: red;" class="fa fa-plus"></i> Add</a>
</ul>


<div class="row mt">
    <div class="col-lg-12">
        <div class="content-panel">
            <div style="padding: 20px;">
                <h4> CUSTOMER </h4>
                <table class="table table-hover" id="myTable">
                    <thead>
                        <tr>
                            <th>
                                #
                            </th>
                            <th>
                                Category Name
                            </th>
                            <th>
                                Number of Products
                            </th>
                            <th>
                                Actions
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr style="padding: 20px;">
                                <td>
                                    @(x++)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.CategoryName)
                                </td>
                                <td>
                                    @db.Product.ToArray().Length
                                </td>
                                <td>
                                    <a href="@Url.Action("Index", "Product", new { id = item.CategoryId })"><i class="fa fa-2x fa-share-square-o"></i></a>
                                    <a href="@Url.Action("Edit", "Category", new { id = item.CategoryId })" data-modal=""><i style="color: sandybrown;" class="fa fa-2x fa-edit"></i></a>
                                    <a href="@Url.Action("Delete", "Category", new { id = item.CategoryId })" data-modal=""><i style="color: red;" class="fa fa-2x fa-trash"></i></a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div><!-- /content-panel -->
    </div><!-- /col-lg-4 -->
</div><!-- /row -->
<!-- modal placeholder-->
<div id='myModal' class='modal fade in'>
    <div class="modal-dialog">
        <div class="modal-content">
            <div id='myModalContent'></div>
        </div>
    </div>
</div>

<script src="~/Scripts/jquery-1.12.4.js"></script>
<script src="~/Scripts/Appjs/IMS.js"></script>

<script>
    $(document).ready(function () {
        $('#myTable').DataTable({
            columnDefs: [
                {
                    targets: [0, 1, 2],
                    className: 'dataTable'
                }
            ]
        });
    });
</script>