IMS/Controllers/AppUserController.cs
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using IMS.Data.Objects.Entities;
using IMS.Data.DbConnections.DAL;
using System;

namespace IMS.Controllers
{
    public class AppUserController : Controller
    {
        private IMS.Data.DbConnections.DAL.IMS_DB db = new IMS.Data.DbConnections.DAL.IMS_DB();

        // GET: AppUser
        public ActionResult Index()
        {
            var appUser = db.AppUser.Include(a => a.Role);
            return View(db.AppUser.ToList());
        }
        

        // GET: AppUser/Register
        public ActionResult Register()
        {
            ViewBag.RoleId = new SelectList(db.Role, "RoleId", "RoleName");
            return View();
        }

        // POST: AppUser/Register
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register([Bind(Include = "AppUserId,AppUserName,AppUserEmail,AppUserPassword,AppUserComfirmPassword,RoleId")] AppUser appUser)
        {
            if (ModelState.IsValid)
            {
                db.AppUser.Add(appUser);
                appUser.RoleId = Convert.ToInt32(Session["role"]);

                
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.RoleId = new SelectList(db.Role, "RoleId", "RoleName", appUser.RoleId);
            return View(appUser);
        }

        // GET: AppUser/Login
        public ActionResult Login()
        {
            return View();
        }

        // POST: AppUser/Login
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(AppUser appUser)
        {
            var user = db.AppUser.Where(ap => ap.AppUserName == appUser.AppUserName && ap.AppUserPassword == appUser.AppUserPassword).SingleOrDefault();
            if (user != null)
            {
                Session["AppUserId"] = user.AppUserId;
                Session["AppUsername"] = user.AppUserName.ToString();
                Session["UserRole"] = user.Role;

                return RedirectToAction("Dashboard");
            }
            else
            {
                ModelState.AddModelError("", "Password doesnt match the Username");
            }
            
            return View();
        }

        //Logged In
        public ActionResult Dashboard()
        {
            if (Session["AppUserId"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Dashboard");
            }
            
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

IMS/Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IMS.Data.Objects.Entities;
using IMS.Data.DbConnections.DAL;

namespace IMS.Controllers
{
    public class RoleController : Controller
    {
        private IMS_DB db = new IMS_DB();

        // GET: /Role/
        public ActionResult Index()
        {
            return View(db.Role.ToList());
        }

        // GET: /Role/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Role role = db.Role.Find(id);
            if (role == null)
            {
                return HttpNotFound();
            }
            return View(role);
        }

        // GET: /Role/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Role/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="RoleId,RoleName")] Role role)
        {
            if (ModelState.IsValid)
            {
                db.Role.Add(role);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(role);
        }

        // GET: /Role/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Role role = db.Role.Find(id);
            if (role == null)
            {
                return HttpNotFound();
            }
            return View(role);
        }

        // POST: /Role/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="RoleId,RoleName")] Role role)
        {
            if (ModelState.IsValid)
            {
                db.Entry(role).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(role);
        }

        // GET: /Role/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Role role = db.Role.Find(id);
            if (role == null)
            {
                return HttpNotFound();
            }
            return View(role);
        }

        // POST: /Role/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Role role = db.Role.Find(id);
            db.Role.Remove(role);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

IMS/Controllers/SaleController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IMS.Data.Objects.Entities;
using IMS.Data.DbConnections.DAL;

namespace IMS.Controllers
{
    public class SaleController : Controller
    {
        private IMS_DB db = new IMS_DB();

        // GET: /Sale/
        public ActionResult Index()
        {
            return View(db.Sale.ToList());
        }

        // GET: /Sale/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sale sale = db.Sale.Find(id);
            if (sale == null)
            {
                return HttpNotFound();
            }
            return PartialView("Details", sale);
        }

        // GET: /Sale/Create
        public ActionResult Create()
        {
            var sale = new Sale();
            return PartialView("Create", sale);
        }

        // POST: /Sale/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Sale sale)
        {
            if (ModelState.IsValid)
            {
                db.Sale.Add(sale);
                db.SaveChanges();
                return Json(new { success = true });
            }

            return PartialView("Create", sale);
        }

        // GET: /Sale/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sale sale = db.Sale.Find(id);
            if (sale == null)
            {
                return HttpNotFound();
            }
            return PartialView("Edit", sale);
        }

        // POST: /Sale/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Sale sale)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sale).State = EntityState.Modified;
                db.SaveChanges();
                return Json(new { success = true });
            }
            return PartialView("Edit", sale);
        }

        // GET: /Sale/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sale sale = db.Sale.Find(id);
            if (sale == null)
            {
                return HttpNotFound();
            }
            return PartialView("Delete", sale);
        }

        // POST: /Sale/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Sale sale = db.Sale.Find(id);
            db.Sale.Remove(sale);
            db.SaveChanges();
            return Json(new { success = true });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

IMS/Controllers/StockController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IMS.Data.Objects.Entities;
using IMS.Data.DbConnections.DAL;

namespace IMS.Controllers
{
    public class StockController : Controller
    {
        private IMS_DB db = new IMS_DB();

        // GET: /Stock/
        public ActionResult Index()
        {
            var stock = db.Stock.Include(s => s.StockCategory).Include(s => s.StockSupplier);
            return View(stock.ToList());
        }

        // GET: /Stock/Details/5
        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Stock stock = db.Stock.Find(id);
        //    if (stock == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(stock);
        //}

        // GET: /Stock/Create
        public ActionResult Create()
        {
            var stock = new Stock();
            ViewBag.CategoryId = new SelectList(db.Category, "CategoryId", "CategoryName");
            ViewBag.SupplierId = new SelectList(db.Suppliers, "SupplierId", "SupplierName");
            return PartialView("Create", stock);
        }

        // POST: /Stock/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="StockId,StockName,StockBuyingPrice,StockSellingPrice,CategoryId,SupplierId")] Stock stock)
        {  
            if (ModelState.IsValid)
            {
                db.Stock.Add(stock);
                db.SaveChanges();
                return Json(new { success = true } );
            }

            ViewBag.CategoryId = new SelectList(db.Category, "CategoryId", "CategoryName", stock.CategoryId);
            ViewBag.SupplierId = new SelectList(db.Suppliers, "SupplierId", "SupplierName", stock.SupplierId);
            return PartialView("Create", stock);
        }

        // GET: /Stock/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Stock stock = db.Stock.Find(id);
            if (stock == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryId = new SelectList(db.Category, "CategoryId", "CategoryName", stock.CategoryId);
            ViewBag.SupplierId = new SelectList(db.Suppliers, "SupplierId", "SupplierName", stock.SupplierId);
            return PartialView("Edit", stock);
        }

        // POST: /Stock/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="StockId,StockName,StockBuyingPrice,StockSellingPrice,CategoryId,SupplierId")] Stock stock)
        {
            if (ModelState.IsValid)
            {
                db.Entry(stock).State = EntityState.Modified;
                db.SaveChanges();
                return Json(new { success = true } );
            }
            ViewBag.CategoryId = new SelectList(db.Category, "CategoryId", "CategoryName", stock.CategoryId);
            ViewBag.SupplierId = new SelectList(db.Suppliers, "SupplierId", "SupplierName", stock.SupplierId);
            return PartialView("Edit", stock);
        }

        // GET: /Stock/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Stock stock = db.Stock.Find(id);
            if (stock == null)
            {
                return HttpNotFound();
            }
            return PartialView("Delete", stock);
        }

        // POST: /Stock/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Stock stock = db.Stock.Find(id);
            db.Stock.Remove(stock);
            db.SaveChanges();
            return Json(new { success = true } );
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

IMS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title -kingsway</title>

    @Scripts.Render("~/bundles/jquery")
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/style.css" rel="stylesheet" />
    <link href="~/Content/style-responsive.css" rel="stylesheet" />

    <link href="~/Content/Datatables/css/jquery.dataTables.css" rel="stylesheet" />
    @*<link href="~/Content/DataTables/css/dataTables.bootstrap.css" rel="stylesheet" />*@
    <link href="~/Content/table-responsive.css" rel="stylesheet" />
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
    <link href="~/Content/to-do.css" rel="stylesheet" />
    <link href="~/Content/zabuto_calendar.css" rel="stylesheet" />

    <!--Date Picker-->
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css" />
</head>
<body>
    @using IMS.Data.Objects.Entities;
    @using IMS.Data.DbConnections.DAL;
    @{
        var role = Session["UserRole"] as Role;
    }
    <section id="container">

        <!--header start-->
        <header class="header black-bg">
            <div class="sidebar-toggle-box">
                <div class="fa fa-bars tooltips" data-placement="right" data-original-title="Toggle Navigation"></div>
            </div>
            <!--logo start-->
            <a href="" class="logo">
                <img src="~/Content/Image/logo-bd.png" width="80" height="24" />
            </a>
            <!--logo end-->
            
            @if (role.CanManageStaff == true)
            {
            <div class="nav notify-row" id="top_menu">
                <!--  notification start -->
                <ul class="nav top-menu">
                    <!-- settings start -->
                    <li class="dropdown">
                        <a data-toggle="dropdown" class="dropdown-toggle" href="">
                            <i class="fa fa-spinner"></i>
                        </a>
                        <ul class="dropdown-menu extended tasks-bar">
                            <div class="notify-arrow notify-arrow-green"></div>
                            <li>
                                <p class="green">SETTINGS</p>
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "Role")">
                                    <div class="task-info">
                                        <div class="desc">
                                            Role Manger
                                        </div>

                                    </div>
                                </a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "AppUser")">
                                    <div class="task-info">
                                        <div class="desc">
                                            Staff Manger
                                        </div>

                                    </div>
                                </a>
                            </li>
                            <li>
                                <a>
                                    <div class="task-info">
                                        <div class="desc">
                                            Logout
                                        </div>

                                    </div>
                                </a>
                            </li>
                            </ul>
                        

                    </li>
                </ul>
                </div>
            }
        </header>

        <!--header end-->
        <!--sidebar start-->
        <aside>
            <div id="sidebar" class="nav-collapse ">
                <!-- sidebar menu start-->
                <ul class="sidebar-menu" id="nav-accordion">

                    <p class="centered"><a href=""><img src="~/Content/Image/fr-05.jpg" class="img-circle" width="60"></a></p>

                    <li class="mt">
                        <a class="active" href="@Url.Action("Index", "Dashboard")">
                            <i class="fa fa-dashboard"></i>
                            <span>Dashboard</span>
                        </a>
                    </li>

                    <li class="sub-menu">
                        <a href="@Url.Action("Index", "Category")">
                            <i class="fa fa-tasks"></i>
                            <span>Categories</span>
                        </a>
                    </li>
                    @if(role.CanManageCustomers == true)
                    {

                    
                    <li class="sub-menu">
                        <a href="@Url.Action("Index", "Customer")">
                            <i class="fa fa-desktop"></i>
                            <span>Customers</span>
                        </a>
                    </li>
                    }
                    <li class="sub-menu">
                        <a href="@Url.Action("Index", "Supplier")">
                            <i class="fa fa-cogs"></i>
                            <span>Suppliers</span>
                        </a>
                        <!--ul class="sub">
                            <li><a href="calendar.html">Calendar</a></li>
                            <li><a href="gallery.html">Gallery</a></li>
                            <li><a href="todo_list.html">Todo List</a></li>
                        </ul-->
                    </li>
                    <li class="sub-menu">
                        <a href="">
                            <i class="fa fa-book"></i>
                            <span>Stocks</span>
                        </a>
                        <ul class="sub">
                            <li><a href="@Url.Action("Index", "Stock")">View Stock</a></li>
                            <li><a href="@Url.Action("Index", "Purchase")">Purchase Stock</a></li>
                            <li><a href="@Url.Action("Index", "Category")">Stock Avaliability</a></li>
                        </ul>
                    </li>
                    <li class="sub-menu">
                        <a href="@Url.Action("Index", "Sale")">
                            <i class="fa fa-th"></i>
                            <span>Sales</span>
                        </a>
                    </li>
                    <li class="sub-menu">
                        <a href="javascript:;">
                            <i class=" fa fa-money"></i>
                            <span>Payments</span>
                        </a>
                    </li>
                    <li class="sub-menu">
                        <a href="javascript:;">
                            <i class=" fa fa-bar-chart-o"></i>
                            <span>Outstanding</span>
                        </a>
                    </li>
                    <li class="sub-menu">
                        <a href="javascript:;">
                            <i class=" fa fa-file-text"></i>
                            <span>Pending</span>
                        </a>
                    </li>
                    <li class="sub-menu">
                        <a href="javascript:;">
                            <i class=" fa fa-th-list"></i>
                            <span>Reports</span>
                        </a>
                    </li>

                </ul>
                <!-- sidebar menu end-->
            </div>
        </aside>
        <!--sidebar end-->


        <section id="main-content">
            <section class="wrapper">

                <!--Rendering Body Start-->
                @RenderBody()

                <!--Rendering Body Start-->
            </section>
        </section>
        <!--footer start-->
        <footer class="site-footer">
            <div class="text-center">
                &copy; @DateTime.Now.Year - Bizzdesk Global Group
                <a href="" class="go-top">
                    <i class="fa fa-angle-up"></i>
                </a>
            </div>
        </footer>
        <!--footer end-->
    </section>


    <!-- js placed at the end of the document so the pages load faster -->
    <script src="~/Scripts/bootstrap.min.js"></script>
    <!--JQuery 1.10.2-->
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="~/Scripts/jquery.dcjqaccordion.2.7.js"></script>
    <script src="~/Scripts/jquery.scrollTo.min.js"></script>
    <script src="~/Scripts/jquery.nicescroll.js"></script>
 

    <script src="~/Scripts/DataTables/jquery.dataTables.js"></script>
    @*<script src="~/Scripts/DataTables/dataTables.bootstrap.js"></script>*@
    <!--common script for all pages-->
    <script src="~/Scripts/common-scripts.js"></script>
    <script src="~/Scripts/gritter-conf.js"></script>

</body>

</html>

IMS/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title -kingsway</title>

    <!-- Bootstrap core CSS -->
    <link href="~/Content/bootstrap.css" rel="stylesheet">
    <!--external css-->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="~/Content/style.css" rel="stylesheet">
    <link href="~/Content/style-responsive.css" rel="stylesheet">

    @Scripts.Render("~/bundles/jquery")

</head>

<body style="background-color: black">
    <div>
        <!--Rendering Body Start-->
            @RenderBody()
        <!--Rendering Body End-->
    </div>

    <!--footer start-->
    @*<footer class="site-footer">
        <div class="text-center">
            &copy; @DateTime.Now.Year - Bizzdesk Global Group
            <a href="" class="go-top">
                <i class="fa fa-angle-up"></i>
            </a>
        </div>
    </footer>*@
    <!--footer end-->



    <!-- js placed at the end of the document so the pages load faster -->
    <script src="~/Scripts/bootstrap.js"></script>

</body>
</html>