IMS/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace IMS.Models
{
    public class Customer
    {
        [Key]
        public int CustomerId { get; set; }

        [Required(ErrorMessage = "Name field required")]
        [Display(Name = "Name")]
        public string CustomerName { get; set; }

        [Required(ErrorMessage = "Address field required")]
        [Display(Name = "Address")]
        public string CustomerAddress { get; set; }

        [Required(ErrorMessage = "Phone number field required")]
        [Display(Name = "Phone Number")]
        public string CustomerContact { get; set; }
    }
}

IMS/Controllers/CustomerController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using IMS.Data.Objects.Entities;
using IMS.Data.DbConnections.DAL;

namespace IMS.Controllers
{
    public class CustomerController : Controller
    {
        private IMS_DB db = new IMS_DB();

        // GET: /Customer/
        public ActionResult Index()
        {
            return View(db.Customers.ToList());
        }

        //Write action for return database data
        //public ActionResult Loaddata()
        //{
        //    using (IMS_DB db = new IMS_DB())
        //    {
        //        var data = db.Customers.OrderBy(c => c.CustomerName).ToList();
        //        return Json(new {data = data}, JsonRequestBehavior.AllowGet);
        //    }
        //}


        // GET: /Customer/Details/5
        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Customer customer = db.Customers.Find(id);
        //    if (customer == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return PartialView("Details", customer);
        //}

        // GET: /Customer/Create
        public ActionResult Create()
        {
            var customer = new Customer();
            return PartialView("Create", customer);
        }

        // POST: /Customer/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="CustomerId,CustomerName,CustomerAddress,CustomerContact")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Customers.Add(customer);
                db.SaveChanges();
                return Json(new { success = true });
            }

            return PartialView("Create", customer);
        }

        // GET: /Customer/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return PartialView("Edit", customer);
        }

        // POST: /Customer/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="CustomerId,CustomerName,CustomerAddress,CustomerContact")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(customer).State = EntityState.Modified;
                db.SaveChanges();
                return Json(new { success = true });
            }
            return PartialView("Edit", customer);
        }

        // GET: /Customer/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return PartialView("Delete", customer);
        }

        // POST: /Customer/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Customer customer = db.Customers.Find(id);
            db.Customers.Remove(customer);
            db.SaveChanges();
            return Json(new { success = true });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

IMS/Views/Customer/Create.cshtml
@model IMS.Data.Objects.Entities.Customer

<!--MODAL HEADER-->
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 class="modal-title">Add New Customer</h3>

</div>

@using (Html.BeginForm("Create", "Customer", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.CustomerId)
    
     <!--MODAL BODY-->
    <div class="modal-body">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12 form-group">
                    @Html.LabelFor(model => model.CustomerName, new { @class = "control-label" })
                    @Html.TextBoxFor(model => model.CustomerName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CustomerName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 form-group">
                    @Html.LabelFor(model => model.CustomerAddress, new { @class = "control-label bold" })
                    @Html.TextBoxFor(model => model.CustomerAddress, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CustomerAddress, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 form-group">
                    @Html.LabelFor(model => model.CustomerContact, new { @class = "control-label" })
                    @Html.TextBoxFor(model => model.CustomerContact, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CustomerContact, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    </div>

        <!--MODAL FOOTER-->
    <div class="modal-footer">
        <input class="btn btn-primary" type="submit" value="Save" />
        <button class="btn btn-warning" data-dismiss="modal">Close</button>
    </div>

}

<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script>
    $("form").removeData("validator");
    $("form").removeData("unobtrusiveValidation");
    $.validator.unobtrusive.parse("form");
</script>

IMS/Views/Customer/Delete.cshtml
@model IMS.Data.Objects.Entities.Customer

<!--MODAL HEADER-->
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 class="modal-title">Deleting Customer</h3>
</div>

<!--MODAL BODY-->
<div class="modal-body">
    <h3>
        Are you sure you want to delete @Html.DisplayFor(model => model.CustomerName)  ?
    </h3>
</div>

    @using (Html.BeginForm("Delete", "Customer", FormMethod.Post)) {
        @Html.AntiForgeryToken()
        
<!--MODAL FOOTER-->
        <div class="modal-footer">
            <input type="submit" value="Yes" class="btn btn-danger" />
            <button class="btn btn-warning" data-dismiss="modal">No</button>
        </div>
    }

IMS/Views/Customer/Edit.cshtml
@model IMS.Data.Objects.Entities.Customer

<!--MODAL HEADER-->
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 class="modal-title">Editing @Html.DisplayFor(model => model.CustomerName)</h3>

</div>

@using (Html.BeginForm("Edit", "Customer", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.CustomerId)
     <!--MODAL BODY-->
    <div class="modal-body">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12 form-group">
                    @Html.LabelFor(model => model.CustomerName, new { @class = "control-label" })
                    @Html.TextBoxFor(model => model.CustomerName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CustomerName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 form-group">
                    @Html.LabelFor(model => model.CustomerAddress, new { @class = "control-label bold" })
                    @Html.TextBoxFor(model => model.CustomerAddress, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CustomerAddress, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 form-group">
                    @Html.LabelFor(model => model.CustomerContact, new { @class = "control-label" })
                    @Html.TextBoxFor(model => model.CustomerContact, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CustomerContact, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    </div>

        <!--MODAL FOOTER-->
    <div class="modal-footer">
        <input class="btn btn-primary" type="submit" value="Save" />
        <button class="btn btn-warning" data-dismiss="modal">Close</button>
    </div>

}

<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script>
    $("form").removeData("validator");
    $("form").removeData("unobtrusiveValidation");
    $.validator.unobtrusive.parse("form");
</script>

IMS/Views/Customer/Index.cshtml
@model IEnumerable<IMS.Data.Objects.Entities.Customer>
@{
    ViewBag.Title = "Index";
    var customer = new IMS.Data.Objects.Entities.Customer();
    var x = 1;
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    td {
        text-align: center;
        vertical-align: middle;
    }

    th {
        text-align: center;
        vertical-align: middle;
    }
</style>

<ul class="breadcrumb">
    <li><a href="@Url.Action("Index", "Dashboard")">Dashboard</a></li>
    <a href="@Url.Action("Create", "Customer")" class="btn btn-primary btn-sm pull-right" data-modal=""><i style="color: red;" class="fa fa-2x fa-plus"></i> Add</a>
</ul>

<div class="row mt">
    <div class="col-lg-12">
        <div class="content-panel">
            <div style="padding: 20px;">
                <h4> CUSTOMER </h4>
                <table class="table table-hover" id="myTable">
                    <thead>
                        <tr>
                            <th>
                                #
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.CustomerName)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.CustomerAddress)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.CustomerContact)
                            </th>
                            <th>
                                Actions
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @(x++)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.CustomerName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.CustomerAddress)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.CustomerContact)
                                </td>
                                <td>
                                    <a href="@Url.Action("Edit", "Customer", new { id = item.CustomerId })" data-modal=""><i style="color: brown;" class="fa fa-2x fa-edit"></i></a>
                                    <a href="@Url.Action("Delete", "Customer", new { id = item.CustomerId })" data-modal=""><i style="color: red;" class="fa fa-2x fa-trash"></i></a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div><!-- /content-panel -->
    </div><!-- /col-lg-4 -->
</div><!-- /row -->
<!-- modal placeholder-->
<div id='myModal' class='modal fade in'>
    <div class="modal-dialog">
        <div class="modal-content">
            <div id='myModalContent'></div>
        </div>
    </div>
</div>

<script src="~/Scripts/jquery-1.12.4.js"></script>
<script src="~/Scripts/Appjs/IMS.js"></script>

<script>
    $(document).ready(function () {
        $('#myTable').DataTable({
            columnDefs: [
                {
                    targets: [0, 1, 2],
                    className: 'dataTable'
                }
            ]
        });
    });
</script>